spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: hoangthanhtuyen.ksmy@gmail.com
    password: dydh mwnn agld cjuu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 5000
          connectiontimeout: 5000
